import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";

import TopNav from "~/components/TopNav";

import "@uploadthing/react/styles.css";
import { GeistSans } from "geist/font/sans";
import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "tcGallery",
  description: "Generated by a loyal subscriber of Theo on YouTube.",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="flex flex-col gap-4">
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
